# Generated by Django 5.1.3 on 2025-06-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bobbin_app', '0002_alter_product_options_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Brand',
            new_name='brand',
        ),
    ]
