# Generated by Django 5.1.3 on 2025-06-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bobbin_app', '0003_rename_brand_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('denim', 'Denim'), ('formal', 'Formal'), ('oversized', 'Oversized')], help_text='Style of the shirt (Casual, Denim, Formal, Oversized)', max_length=100, null=True),
        ),
    ]
