# Generated by Django 5.1.3 on 2025-06-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bobbin_app', '0009_alter_productimage_alt_text_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, choices=[('cotton', 'Cotton'), ('linen', 'Linen'), ('denim', 'Denim'), ('flannel', 'Flannel'), ('polyester', 'Polyester'), ('rayon', 'Rayon / Viscose'), ('blends', 'Blends'), ('silk', 'Silk')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('beige', 'Beige'), ('grey', 'Grey'), ('brown', 'Brown'), ('pink', 'Pink')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=10, null=True),
        ),
    ]
