# Generated by Django 5.1.3 on 2025-07-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bobbin_app', '0011_userpincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('denim', 'Denim'), ('formal', 'Formal'), ('oversized', 'Oversized'), ('printed', 'Printed'), ('checked', 'Checked'), ('striped', 'Striped'), ('solid', 'Solid'), ('cuban', 'Cuban'), ('half sleeve', 'Half Sleeve'), ('full sleeve', 'Full Sleeve')], help_text='Category of the shirt (Casual, Denim, Formal, Printed, etc.)', max_length=100, null=True),
        ),
    ]
